services:
  jira:
    build: .
    container_name: jira-srv
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./storage/jira:/var/jira
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8.0
    container_name: mysql-jira
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

  phpmyadmin:
    container_name: phpmyadmin-jira
    env_file:
      - .env
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100M
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
