version: '3.4'
services:
  jira:
    build: .
    container_name: jira-srv
    env_file:
      - .env
    environment:
#      - JVM_MINIMUM_MEMORY=1g
#      - JVM_MAXIMUM_MEMORY=12g
#      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./storage/jira:/var/jira
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mariadb:10.6
    container_name: mysql-jira
    env_file:
      - .env
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

  phpmyadmin:
    container_name: phpmyadmin-jira
    env_file:
      - .env
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100M
    networks:
      network-bridge

networks:
  network-bridge:
    driver: bridge
